### ISSUE TITLE
Performance: Consider removing default AnimationFrameScheduler in withRX2

### ISSUE THREAD

**Issue by raveclassic** [devex-web-frontend/dx-platform#141]
Current implementation of `withRX2` observers the source on `animationFrame` scheduler by default. This leads to a case when inactive tab is processing websocket messages delaying execution of the stream to the next animation frame. In its turn this leads to a freeze on tab activation because scheduler is trying to flush all buffered work.

We should discuss wether it's the responsibility of the end project to skip/buffer socket messages or withRX should be scheduler-agnostic and we should improve its API.

/cc @sutarmin @dramoturg

**Comment by sutarmin** [comment]
As I remember, the possibility to set custom scheduler in `withRX` was implemented for unit testing primarily. Now we have two options:
1) Change default scheduler to be AsyncScheduler, [which usees setInterval instead of rAF](https://github.com/ReactiveX/rxjs/blob/6.x/src/internal/scheduler/AsyncAction.ts#L72)
2) Create helper like `makeWithRX: WithRXOptions -> typeof withRX`. This would give us flexibility in this question without a huge breaking change

I'm for the latter one.

**Comment by raveclassic** [comment]
The problem is not in the scheduler itself. It's actually normal to calls to setState on next frame. The problem here is that updates to different parts of UI are flushed together on the next frame (on tab activation) and that's why the app freezes, not because of "buffering" events in the stream, they are not buffered afaics.
