### ISSUE TITLE
Why anchor optional when render return null if anchor === undefined

### ISSUE THREAD

**Issue by Sky161** [devex-web-frontend/dx-platform#85]
https://github.com/devex-web-frontend/dx-platform/blob/d1f683bf9545a53e9f486922bcf7d21736e375af/packages/react-kit/src/components/Popover/Popover.tsx#L46

https://github.com/devex-web-frontend/dx-platform/blob/d1f683bf9545a53e9f486922bcf7d21736e375af/packages/react-kit/src/components/Popover/Popover.tsx#L150

**Comment by sutarmin** [comment]
That's a great question, actually.
Popover component cannot be rendered with `anchor === undefined` because it cannot calulate position for itself. But, with optional anchor, we can write
```
<Button ref={el => (this.popoverAnchor = el)} ...>
    <Popover
        anchor={this.popoverAnchor}
        ...
    />
</ButtonIcon>
```
and when component renders first time `el => (this.popoverAnchor = el)` callback wasn't run yet. We can pass it "as is" to `Popover` component and it will just render null. With non-optional anchor we should control rendering from outside of the Popover, like this:
```
<Button ref={el => (this.popoverAnchor = el)} ...>
    {this.popoverAnchor && (
        <Popover
            anchor={this.popoverAnchor}
            ...
        />
)}
</ButtonIcon>
```
The former gives better DX to some extent (easier to write/read, don't have to think about `undefined` case), the latest is better from the perspective of component APIs and responsibilities (why should `Popover` know what to do when it doesn't have all of nesseary properties). So we have two options here
1) Leave this as it is.
2) [BREAKING] Change anchor prop to `anchor: Component<P> | Element` (ReactRef doen't fit, it includes `null` which is also invalid)

@devex-web-frontend/team , opinions?

**Comment by sutarmin** [comment]
`current` property on RefObject [has type `T | null`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/0125d65fd50252f27cd85e49b0cfa4dd2819faf0/types/react/index.d.ts#L58) so ref api still has this issue. Looks like current approach (checking for `!anchor` inside Popover component) would play better with React 16 refs.

**Comment by sutarmin** [comment]
How will this help? You'll still need to check ref for not been `null`. With `unknown` you need to check even more things, actually. 

The question of this discussion is "should we check if ref is `null | undefined` inside Popover or restrict props type so Popover accept only non-nullable ref value?".

**Comment by raveclassic** [comment]
The point is to remove null and undefined from prop types, it doesnt matter what checks are hidden inside the component.
React provides dedicated type for all refs so let's just use it.

**Comment by sutarmin** [comment]
Got your point. So the answer to this question is: "Popover is not intended to work without the anchor, API will change when w migrate to React 16 ref api". The question is answered, I'll create new issue for migrating
